---
name: "tests"

on: push

jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: icepuma/rust-action@master
        with:
          args: cargo test 

